version: '3'
services:
    less_redis:
        image: redis
        ports: ["6379:6379"]
        entrypoint: redis-server
    less_mysql:
        image: mysql:5
        ports: ["3306:3306"]
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: proj
        command:
          - mysqld
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
          - "--default-time-zone=+08:00"
          - "--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
# run: docker-compose up
# remove: docker-compose down -v