from typing import Callable, Type, Dict, Any, List, Tuple

from lessweb.context import Context


__all__ = ['request_bridge']


def model_or_service(cls: Type) -> int: ...
def fetch_service(ctx: Context, service_type: Type) -> Any: ...
def request_bridge(inputval: Any, target_type: Type) -> Any: ...
def fetch_model(ctx: Context, target_type: Type) -> Any: ...
def fetch_param(ctx: Context, fn: Callable) -> Tuple[List, Dict[str, Any]]: ...
