from typing import Callable, Type, TypeVar, Generic, Dict, Any

from lessweb.context import Context


__all__ = ["Model", "Service"]


T = TypeVar('T')


class Model(Generic[T]):
    value: T
    def __init__(self, value: T) -> None: ...
    def __call__(self) -> T: ...
    def __str__(self) -> str: ...


class Service(Generic[T]):
    value: T
    def __init__(self, value: T) -> None: ...
    def __call__(self) -> T: ...
    def __str__(self) -> str: ...


def fetch_service(ctx: Context, service_type: Type) -> Any: ...
def fetch_model(ctx: Context, core_type: Type, origin_type: Type) -> Any: ...
def fetch_param(ctx: Context, fn: Callable) -> Dict[str, Any]: ...
