from typing import Callable, Type, Dict, Any

from lessweb.context import Context


__all__ = ['request_bridge']


def model_or_service(cls: Type) -> int: ...
def fetch_service(ctx: Context, service_type: Type) -> Any: ...
def request_bridge(inputval: Any, target_type: Type) -> Any: ...
def fetch_param(ctx: Context, fn: Callable) -> Dict[str, Any]: ...
