__all__ = ["make_resolver", "validate", "parse_value", "check_param_str"]


def make_resolver(openapi): ...
def validate(instance, *, schema, resolver) -> str: ...
def parse_value(string, schema_type): ...
def check_param_str(param_name, *, param_value, schema, resolver): ...
