__all__ = ["Storage"]


class Storage(dict):
    def __getattr__(self, key): ...
    def __setattr__(self, key, value): ...
    def __delattr__(self, key): ...
    def __repr__(self): ...
    def __sub__(self, other): ...
    @staticmethod
    def of(obj) -> 'Storage': ...
